// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.K8sdatadog
{
    [K8sdatadogResourceType("k8sdatadog:index:K8sMonitor")]
    public partial class K8sMonitor : global::Pulumi.ComponentResource
    {
        /// <summary>
        /// Namespace in which datadog agent is installed.
        /// </summary>
        [Output("namespace")]
        public Output<string> Namespace { get; private set; } = null!;


        /// <summary>
        /// Create a K8sMonitor resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public K8sMonitor(string name, K8sMonitorArgs args, ComponentResourceOptions? options = null)
            : base("k8sdatadog:index:K8sMonitor", name, args ?? new K8sMonitorArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumi-pequod/pequod-mlc-k8sdatadog",
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class K8sMonitorArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Datadog API key needed by k8s agent to communicate with Datadog
        /// </summary>
        [Input("apiKey", required: true)]
        public Input<string> ApiKey { get; set; } = null!;

        public K8sMonitorArgs()
        {
        }
        public static new K8sMonitorArgs Empty => new K8sMonitorArgs();
    }
}
